# Generated by Django 2.2 on 2022-12-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfPatient', models.CharField(max_length=25)),
                ('medicalCondition', models.CharField(max_length=100)),
            ],
        ),
    ]
